# Generated by Django 2.2.5 on 2019-09-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manaCost', models.CharField(max_length=50)),
                ('cmc', models.FloatField()),
                ('type', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=20)),
                ('set', models.CharField(max_length=2)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
