# Generated by Django 2.2.5 on 2019-09-10 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manaCost', models.CharField(blank=True, max_length=50)),
                ('cmc', models.FloatField()),
                ('type', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=20)),
                ('set', models.CharField(max_length=50)),
                ('text', models.CharField(blank=True, max_length=800)),
                ('imageUrl', models.CharField(blank=True, max_length=300)),
                ('users', models.ManyToManyField(related_name='collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imageUrl', models.CharField(blank=True, max_length=300)),
                ('win_rate', models.FloatField(blank=True, null=True)),
                ('cards', models.ManyToManyField(related_name='decks', to='mtg_decks.Card')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks_created', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='decks_played', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_created', to=settings.AUTH_USER_MODEL)),
                ('decks', models.ManyToManyField(related_name='games', to='mtg_decks.Deck')),
                ('users', models.ManyToManyField(related_name='games_played', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
