# Generated by Django 2.2.5 on 2019-09-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_decks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='set',
            field=models.CharField(max_length=3),
        ),
    ]
