# Generated by Django 2.2.5 on 2019-09-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_decks', '0002_auto_20190905_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
