# Generated by Django 2.2.5 on 2019-09-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_decks', '0003_auto_20190905_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.CharField(max_length=800),
        ),
    ]
