# Generated by Django 2.2.5 on 2019-09-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_decks', '0004_auto_20190905_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
