# Generated by Django 2.2.5 on 2019-09-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_decks', '0005_auto_20190905_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='image',
            new_name='imageUrl',
        ),
    ]
