# Generated by Django 2.2.5 on 2019-09-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_decks', '0006_auto_20190905_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='set',
            field=models.CharField(max_length=50),
        ),
    ]
