# Generated by Django 2.2.5 on 2019-09-05 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_decks', '0009_auto_20190905_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deck',
            name='users',
            field=models.ManyToManyField(related_name='decks_played', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_by',
            field=models.ManyToManyField(related_name='games_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games_played', to=settings.AUTH_USER_MODEL),
        ),
    ]
