# Generated by Django 2.2.5 on 2019-09-05 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_decks', '0010_auto_20190905_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_by',
            field=models.ManyToManyField(related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
