# Generated by Django 2.2.5 on 2019-09-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_decks', '0014_card_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='win_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
