# Generated by Django 2.2.5 on 2019-09-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_decks', '0016_auto_20190905_2048'),
        ('mtg_decks', '0016_auto_20190905_2043'),
    ]

    operations = [
    ]
